#ifndef __MYSQL_SPHERE_TYPES__
#define __MYSQL_SPHERE_TYPES__

enum MYSQL_SPHERE_TYPES {
	MYSQL_SPHERE_UNKNOWN = 0,
	MYSQL_SPHERE_POINT = 1,
	MYSQL_SPHERE_EULER = 2,
	MYSQL_SPHERE_CIRCLE = 3,
	MYSQL_SPHERE_LINE = 4,
	MYSQL_SPHERE_ELLIPSE = 5,
	MYSQL_SPHERE_POLYGON = 6,
	MYSQL_SPHERE_PATH = 7,
	MYSQL_SPHERE_BOX = 8
};

#endif